# Generated by Django 3.2.7 on 2021-09-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='blood_group',
            new_name='course',
        ),
    ]
